### ISSUE TITLE
Error when running, google_client_secrets.json

### ISSUE THREAD

**Issue by samgiagtzoglou** [wesleyan/pulleffect#2]
Getting an error when running...

```
Traceback (most recent call last):
  File "runserver.py", line 1, in <module>
    from pulleffect import app
  File "/Users/Sam/Desktop/pulleffect/pulleffect/__init__.py", line 13, in <module>
    from pulleffect.lib.google.gcal import gcal
  File "/Users/Sam/Desktop/pulleffect/pulleffect/lib/google/gcal.py", line 22, in <module>
    google_client_secrets = json.load(open(config["google_client_secrets"])).get("web")
IOError: [Errno 2] No such file or directory: u'./pulleffect/config/google_client_secrets.json'
```

Is ./pulleffect/config/google_client_secrets.json supposed to exist somewhere, and someone didn't commit it? Or am I missing something?

**Comment by artburkart** [comment]
It's not supposed to be committed. If you went through the commit history,
you would have found it, but here it is anyway.

**Comment by samgiagtzoglou** [comment]
Ah sorry - before I looked back to one commit short. Found out, thanks

**Comment by artburkart** [comment]
Not an issue, at some point the client secret will need to change to a
pulleffect@gmail.com account and then everything will change so there is no
point in keeping it in the git repo. It's also supposed to be secret, so
please don't add it back in.
