### ISSUE TITLE
installing requirements.txt

### ISSUE THREAD

**Issue by barca** [wesleyan/pulleffect#3]
an issue arises when attempting to set up a development environment: 
pip install -r requirements.txt

Requirement already satisfied (use --upgrade to upgrade): argparse==1.2.1 in /usr/lib/python2.7 (from -r requirements.txt (line 9))
Downloading/unpacking cx-Oracle==5.1.2 (from -r requirements.txt (line 10))
  Could not find any downloads that satisfy the requirement cx-Oracle==5.1.2 (from -r requirements.txt (line 10))
  Some externally hosted files were ignored (use --allow-external cx-Oracle to allow).
Cleaning up...
No distributions at all found for cx-Oracle==5.1.2 (from -r requirements.txt (line 10))
Storing debug log for failure in /home/tylerharden/.pip/pip.log

**Comment by artburkart** [comment]
You may need to manually install cx_Oracle
