### ISSUE TITLE
Logging in with wrong email

### ISSUE THREAD

**Issue by bgapinski** [wesleyan/pulleffect#4]
There should be a button or something to log out / switch accounts when you don't initially log in with your wes email.

**Comment by artburkart** [comment]
lol, I was just talking about this with Jack yesterday and decided it
wasn't a big deal since you and I are the only ones that use our gmails

**Comment by artburkart** [comment]
test response

**Comment by artburkart** [comment]
It's no longer an issue because we switched to Flask_CAS
