### ISSUE TITLE
Timeclock widget appearance/reporting

### ISSUE THREAD

**Issue by rchristensen** [wesleyan/pulleffect#5]
The timeclock widget should display the following:

username - scheduled shift time - clocked in? - report button

Obviously with whatever visual flair you wish, but the clocked in icon should change to absent for confirmed absences (reported via the gcal pulleffect is reporting from)

The report button should be a manual way to report a strike in the short term.  Could simply dispatch an e-mail to certain folks.  In the long term, it should be automated based on times management agrees on, ex: automatic warning for 7 minute late clock in, automatic strike for 15 minute clock in.  I think this would depend on our database project.

**Comment by artburkart** [comment]
Okay, sounds good. It'll be done by the end of next week for sure.

**Comment by artburkart** [comment]
The route is complete.
/shifts/authenticate
/shifts?id=(calendar_id)
