### ISSUE TITLE
Competition Widget

### ISSUE THREAD

**Issue by rchristensen** [wesleyan/pulleffect#6]
Besides ticket resolution data from ServiceNow, the 'competition' widget should track on-time clock-ins and events performance from spec and generate a ranking.  There needs to be a discussion between managers on how this should be calculated

**Comment by artburkart** [comment]
clock-ins? I was just discussing this with Brian. Is this on a departmental basis, or is this at an individual level? Isn't that sort of information privileged?

**Comment by rchristensen** [comment]
For the widget, it's an aggregate. The competition widget ranks people by performance in IMS.  Obviously ticket resolutions are doable, but it should be more.  On-time clock-ins, people should get a point or whatever every time they clock in for their scheduled shift during our predetermined window (2pts for within 1 minute, 1 point within 3, or something to that effect).

People's schedules and whether or not they were on time is not privileged information.. regardless, the raw data shouldn't be viewable by just anyone.

**Comment by rchristensen** [comment]
Relevant documentation for SN:

http://wiki.servicenow.com/index.php?title=JSON_Web_Service
